BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Result';
EXCEPTION
WHEN OTHERS THEN
IF SQLCODE != -942 THEN
RAISE;
END IF;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Stud_Marks';
EXCEPTION
WHEN OTHERS THEN
IF SQLCODE != -942 THEN
RAISE;
END IF;
END;

CREATE TABLE Stud_Marks (
Roll NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Name VARCHAR2(50),
total_marks NUMBER
);
CREATE TABLE Result (
Roll NUMBER PRIMARY KEY,
Name VARCHAR2(50),
Class VARCHAR2(20)
);

INSERT INTO Stud_Marks (Name, total_marks) VALUES ('Alice', 1450);
INSERT INTO Stud_Marks (Name, total_marks) VALUES ('Bob', 980);
INSERT INTO Stud_Marks (Name, total_marks) VALUES ('Charlie', 920);
INSERT INTO Stud_Marks (Name, total_marks) VALUES ('David', 870);
INSERT INTO Stud_Marks (Name, total_marks) VALUES ('Eve', 800);
COMMIT;
CREATE OR REPLACE PROCEDURE proc_Grade (
p_Roll IN NUMBER,
p_Name IN VARCHAR2,
p_TotalMarks IN NUMBER
) AS
v_Class VARCHAR2(20);
BEGIN
IF p_TotalMarks <= 1500 AND p_TotalMarks >= 990 THEN
v_Class := 'Distinction';
ELSIF p_TotalMarks BETWEEN 900 AND 989 THEN
v_Class := 'First Class';
ELSIF p_TotalMarks BETWEEN 825 AND 899 THEN
v_Class := 'Higher Second Class';
ELSE
v_Class := 'No Class';
END IF;
INSERT INTO Result (Roll, Name, Class) VALUES (p_Roll, p_Name, v_Class);
COMMIT;
END;
/

BEGIN
FOR rec IN (SELECT Roll, Name, total_marks FROM Stud_Marks) LOOP
proc_Grade(rec.Roll, rec.Name, rec.total_marks);
END LOOP;
END;
/