SHOW DATABASES;

USE COLLEGE;

SHOW TABLES;

SELECT * FROM STUDENTS;

SELECT * FROM COURSE;

CREATE TABLE COURSE_2(ID INT, COURSE_NAME VARCHAR(20), GUIDE VARCHAR(20));

INSERT INTO COURSE_2(ID, COURSE_NAME, GUIDE) VALUES
(21, 'CS', 'DR_SHINDE'),
(22, 'IT', 'DR_PATIL'),
(23, 'AI', 'DR_JADHAV'),
(24, 'DS', 'DR_KULKARNI'),
(25, 'MBA', 'DR_THAKARE'),
(26, 'BIOTECH', 'DR_BHIDE'),
(27, 'LAW', 'DR_SALUNKHE'),
(28, 'MEDICAL', 'DR_JOSHI'),
(29, 'PSYCHOLOGY', 'DR_PHADKE');

SELECT * FROM COURSE_2;

SELECT * FROM DETAILS;
SELECT STU_ID AS ID, COURSE_NAME, GUIDE FROM COURSE
UNION ALL
SELECT ID, COURSE_NAME, GUIDE FROM COURSE_2
UNION ALL
SELECT ID, COURSE_NAME, GUIDE FROM DETAILS;