CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE STUDENTS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(20)
);

INSERT INTO STUDENTS (ID, NAME)
VALUES
  (1, "ATHARVA"),
  (2, "PRIYA"),
  (3, "RAHUL"),
  (4, "SNEHA"),
  (5, "AMAN"),
  (6, "KAVYA"),
  (7, "ROHAN"),
  (8, "NISHA"),
  (9, "VIKRAM"),
  (10, "TANYA"),
  (11, "SACHIN");

CREATE TABLE COURSE (
  ID INT PRIMARY KEY,
  COURSE_NAME VARCHAR(20),
  GUIDE VARCHAR(20)
);

INSERT INTO COURSE (ID, COURSE_NAME, GUIDE)
VALUES
  (1, "CS", "DR_PATIL"),
  (2, "IT", "DR_GHOLAB"),
  (3, "ENTC", "DR_SHAH"),
  (4, "MECH", "DR_KULKARNI"),
  (5, "CIVIL", "DR_DESHMUKH"),
  (6, "EEE", "DR_RAO"),
  (7, "AI", "DR_JOSHI"),
  (8, "DS", "DR_MEHTA"),
  (9, "CHEM", "DR_SINGH"),
  (10, "BIOTECH", "DR_KHAN"),
  (11, "ROBOTICS", "DR_CHOPRA"),
  (12, "CS", "DR_PATIL"),
  (13, "IT", "DR_DESHMUKH");

SELECT *
FROM STUDENTS
INNER JOIN COURSE ON STUDENTS.ID = COURSE.ID;

SELECT A.ID, A.NAME
FROM STUDENTS AS A
LEFT JOIN COURSE AS B ON A.ID = B.ID
WHERE B.ID IS NULL;

SELECT B.ID, B.COURSE_NAME, B.GUIDE
FROM STUDENTS AS A
RIGHT JOIN COURSE AS B ON A.ID = B.ID
WHERE A.ID IS NULL;





